version: '3.9'

services:

  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: urban_db
    ports:
      - "5432:5432"

  mongodb:
    image: mongo
    container_name: mongo_db
    ports:
      - "27017:27017"

  python_app:
    build: .
    container_name: python_app
    volumes:
      - .:/app
    depends_on:
      - postgres
      - mongodb
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: "5432"
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: urban_db
      MONGO_HOST: mongodb
      MONGO_PORT: "27017"
    command: tail -f /dev/null

  api:
    build: .
    container_name: api
    working_dir: /app
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: "5432"
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: urban_db
      MONGO_HOST: mongodb
      MONGO_PORT: "27017"
    depends_on:
      - postgres
      - mongodb
    restart: unless-stopped

  dashboard:
    image: nginx:alpine
    container_name: dashboard
    volumes:
      - ./Dashboard:/usr/share/nginx/html:ro
      - ./Dashboard/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8050:80"
    depends_on:
      - api
    restart: unless-stopped

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"

  mongo_express:
    image: mongo-express
    container_name: mongo_express
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: pass
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    restart: always